Clarify Generator construction with required kind
w3c/mediacapture-transform pull request #18
Opened 2021-03-08 10:45 UTC by tprice11

Update description of MediaStreamTrackGenerator to be shorter and clearer that kind is now required by removing the descriptions of handling an empty kind.

2021-03-08 10:52 UTC, dontcallmedom commented
@trpice11 could you provide your changes to the index.bs file instead of the (automatically generated) index.html - I'll separately clarify both the set up and the documentation of the repo to make it clearer that this is the preferred way to contribute.

2021-04-08 16:14 UTC, guidou approved these changes

2021-04-28 15:28 UTC, dontcallmedom requested changes
please bring changes to the index.bs file instead

2022-01-07 14:46 UTC, alvestrand commented
Obsoleted by the change from MediaStreanTrackGenerator(kind) to VideoTrackGenerator.

2022-01-07 14:46 UTC, closed without merging